# Generated by Django 4.1.5 on 2023-01-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa urządzenia')),
                ('pin', models.PositiveSmallIntegerField(unique=True, verbose_name='Pin')),
                ('is_out', models.BooleanField(default=1, verbose_name='Wyjście')),
                ('state', models.BooleanField(default=1, verbose_name='Stan')),
                ('channel', models.FloatField(blank=True, null=True, verbose_name='Kanał')),
            ],
            options={
                'verbose_name': 'Urządzenie wykonawcze',
                'verbose_name_plural': 'Urządzenia wykonawcze',
            },
        ),
        migrations.CreateModel(
            name='MeasuringDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa urządzenia')),
                ('pin', models.PositiveSmallIntegerField(unique=True, verbose_name='Pin')),
                ('is_out', models.BooleanField(default=1, verbose_name='Wyjście')),
            ],
            options={
                'verbose_name': 'Urządzenie pomiarowe',
                'verbose_name_plural': 'Urządzenia pomiarowe',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Nazwa jednostki')),
                ('unit', models.CharField(max_length=5, unique=True, verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametry',
            },
        ),
        migrations.CreateModel(
            name='Setpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Zadana wartość')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.parameter', verbose_name='Parametr')),
            ],
            options={
                'verbose_name': 'Zadana wartość',
                'verbose_name_plural': 'Zadane wartości',
            },
        ),
        migrations.CreateModel(
            name='PointValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Wartość pomiaru')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data pomiaru')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.measuringdevice', verbose_name='Urządzenie')),
            ],
            options={
                'verbose_name': 'Pomiar',
                'verbose_name_plural': 'Pomiary',
            },
        ),
        migrations.AddField(
            model_name='measuringdevice',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aquarium.parameter', verbose_name='Mierzone wartości'),
        ),
    ]
