# Generated by Django 4.1.5 on 2023-01-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldata',
            options={'verbose_name': 'Pomiar historyczny', 'verbose_name_plural': 'Pomiary historyczne'},
        ),
        migrations.AlterModelOptions(
            name='measurementtype',
            options={'verbose_name': 'Typ pomiaru', 'verbose_name_plural': 'Typy pomiarów'},
        ),
        migrations.AlterModelOptions(
            name='measuringdevice',
            options={'verbose_name': 'Urządzenie pomiarowe', 'verbose_name_plural': 'Urządzenia pomiarowe'},
        ),
    ]
