# Generated by Django 4.1.5 on 2023-01-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuringdevice',
            name='parameter',
        ),
    ]
