# Generated by Django 4.1.5 on 2023-01-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0002_remove_measuringdevice_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceParameterMeasured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.measuringdevice', verbose_name='Urządzenie')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.parameter', verbose_name='Parametr')),
            ],
            options={
                'verbose_name': 'Wartość zbierana przez urządzenie',
                'verbose_name_plural': 'Wartości zbierane przez urządzenie',
            },
        ),
    ]
