# Generated by Django 4.1.5 on 2023-01-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0003_deviceparametermeasured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceparametermeasured',
            options={'verbose_name': 'Wartość zbierana przez urządzenie', 'verbose_name_plural': 'Wartości zbierane przez urządzenia'},
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(max_length=5, verbose_name='Jednostka'),
        ),
    ]
