# Generated by Django 4.1.5 on 2023-01-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0004_alter_deviceparametermeasured_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuringdevice',
            name='pin',
        ),
        migrations.AddField(
            model_name='measuringdevice',
            name='address',
            field=models.CharField(default=1, max_length=4, unique=True, verbose_name='Pin lub adres'),
            preserve_default=False,
        ),
    ]
