# Generated by Django 4.1.5 on 2023-01-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0006_measuringdevice_is_i2c'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='processed_name',
            field=models.CharField(default='pizdeusz', max_length=32, unique=True, verbose_name='Angielska nazwa'),
            preserve_default=False,
        ),
    ]
