# Generated by Django 4.1.5 on 2023-01-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0007_parameter_processed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvalue',
            name='parameter',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='aquarium.parameter', verbose_name='Parametr'),
            preserve_default=False,
        ),
    ]
