# Generated by Django 4.1.5 on 2023-01-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0010_tasksequence_tasksequencedevice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSequenceDevice',
            new_name='TaskSequenceStep',
        ),
    ]
