# Generated by Django 4.1.5 on 2023-01-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0011_rename_tasksequencedevice_tasksequencestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpoint',
            name='is_max',
            field=models.BooleanField(default=True, verbose_name='Czy wartośc maksymalna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setpoint',
            name='sequence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='aquarium.tasksequence', verbose_name='Sekwencja uruchamiana w przypadku przekroczenia progu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksequencestep',
            name='output_value',
            field=models.BooleanField(default=True, verbose_name='Stan'),
        ),
    ]
