# Generated by Django 4.1.5 on 2023-01-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0012_setpoint_is_max_setpoint_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpoint',
            name='is_max',
            field=models.BooleanField(verbose_name='Czy wartość maksymalna'),
        ),
        migrations.AlterField(
            model_name='setpoint',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aquarium.tasksequence', verbose_name='Sekwencja uruchamiana w przypadku przekroczenia progu'),
        ),
    ]
