# Generated by Django 4.1.5 on 2023-01-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0014_tasksequence_is_active_taskprecedingsequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskprecedingsequence',
            old_name='sequence',
            new_name='executed_sequence',
        ),
    ]
