# Generated by Django 4.1.5 on 2023-01-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0015_rename_sequence_taskprecedingsequence_executed_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setpoint',
            name='is_max',
        ),
        migrations.AddField(
            model_name='tasksequence',
            name='hysteresis',
            field=models.SmallIntegerField(default=2, verbose_name='Histereza'),
        ),
    ]
