# Generated by Django 4.1.5 on 2023-01-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0016_remove_setpoint_is_max_tasksequence_hysteresis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setpoint',
            name='sequence',
        ),
        migrations.AddField(
            model_name='tasksequence',
            name='setpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquarium.setpoint', verbose_name='Powiązana wartość zadana'),
        ),
    ]
