# Generated by Django 4.1.5 on 2023-01-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0017_remove_setpoint_sequence_tasksequence_setpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksequence',
            name='hysteresis',
            field=models.FloatField(default=2, verbose_name='Histereza'),
        ),
    ]
