# Generated by Django 4.1.5 on 2023-01-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0018_alter_tasksequence_hysteresis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksequence',
            name='comparator',
            field=models.CharField(default='', max_length=4, verbose_name='Komparator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksequence',
            name='hysteresis',
            field=models.IntegerField(default=2, verbose_name='Histereza'),
        ),
    ]
