# Generated by Django 4.1.5 on 2023-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0020_alter_tasksequence_hysteresis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpoint',
            name='value',
            field=models.FloatField(verbose_name='Zadana wartość'),
        ),
    ]
