# Generated by Django 4.1.5 on 2023-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0021_alter_setpoint_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivedevice',
            name='cron',
            field=models.BooleanField(default=False, verbose_name='Przełączanie przez cron'),
        ),
    ]
