# Generated by Django 4.1.5 on 2023-01-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0022_executivedevice_cron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivedevice',
            name='cron',
        ),
    ]
