# Generated by Django 4.1.5 on 2023-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0024_executivedevice_cron'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksequence',
            name='startup_value',
            field=models.BooleanField(default=False, verbose_name='Stan przy uruchomieniu'),
        ),
    ]
