version: "3.9"

services:
  db:
    container_name: aqua-db
    image: mariadb:10.7
    ports:
      - "3306:3306"
    restart: unless-stopped
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_volume:/var/lib/mysql:rw
      - mysqld:/var/run/mysqld
    env_file:
      - ./src/env_vars/.env_db_mysql
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    stop_grace_period: 1m
    healthcheck:
      test: mysqladmin ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    container_name: aqua-redis
    restart: unless-stopped
    image: redis:6
    ports:
      - "6379:6379"

secrets:
  MYSQL_USER:
    file: ./src/env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./src/env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./src/env_vars/.MYSQL_ROOT_PASSWORD

volumes:
  mysql_volume:
  mysqld: # mysql unix socket
